# Generated by Django 4.2.21 on 2025-08-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskcompletion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
