# Generated by Django 4.2.21 on 2025-11-14 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_subject_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'title')},
        ),
    ]
