# Generated by Django 4.2.21 on 2026-03-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_agentchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('encrypted_refresh_token', models.TextField()),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_preset', models.CharField(choices=[('today', 'Today'), ('this_week', 'This Week'), ('custom', 'Custom')], max_length=20)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('emails_scanned_count', models.PositiveIntegerField(default=0)),
                ('suggestions_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='main.emailintegration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('task', 'Task'), ('event', 'Event')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source_message_refs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suggestions', to='main.event')),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suggestions', to='main.task')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='main.emailsyncrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20)),
                ('state_hash', models.CharField(max_length=255, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emailsyncrun',
            index=models.Index(fields=['user', 'status', 'created_at'], name='main_emails_user_id_9e5d24_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsyncrun',
            index=models.Index(fields=['integration', 'created_at'], name='main_emails_integra_59165a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuggestion',
            index=models.Index(fields=['user', 'status', 'created_at'], name='main_emails_user_id_35ae32_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuggestion',
            index=models.Index(fields=['sync_run', 'created_at'], name='main_emails_sync_ru_1416f2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuggestion',
            index=models.Index(fields=['suggestion_type'], name='main_emails_suggest_e322ec_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoauthstate',
            index=models.Index(fields=['user', 'provider', 'expires_at'], name='main_emailo_user_id_74d5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailintegration',
            index=models.Index(fields=['user', 'provider', 'is_active'], name='main_emaili_user_id_8e4d17_idx'),
        ),
        migrations.AddIndex(
            model_name='emailintegration',
            index=models.Index(fields=['provider_account_id'], name='main_emaili_provide_32c105_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailintegration',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_email_provider'),
        ),
    ]
