# Generated by Django 4.2.21 on 2026-03-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_emailintegration_emailsyncrun_emailsuggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('encrypted_subject', models.TextField(blank=True)),
                ('encrypted_body', models.TextField(blank=True)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='emailsuggestion',
            name='ai_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailsuggestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailsuggestion',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailsyncrun',
            name='date_preset',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailsuggestion',
            index=models.Index(fields=['fingerprint'], name='main_emails_fingerp_493944_idx'),
        ),
        migrations.AddField(
            model_name='emailsyncedmessage',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_messages', to='main.emailintegration'),
        ),
        migrations.AddField(
            model_name='emailsyncedmessage',
            name='sync_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_messages', to='main.emailsyncrun'),
        ),
        migrations.AddField(
            model_name='emailsyncedmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_synced_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailsyncedmessage',
            index=models.Index(fields=['user', 'expires_at'], name='main_emails_user_id_b1a2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsyncedmessage',
            index=models.Index(fields=['integration', 'received_at'], name='main_emails_integra_d72eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsyncedmessage',
            index=models.Index(fields=['sync_run', 'stored_at'], name='main_emails_sync_ru_aef98f_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailsyncedmessage',
            constraint=models.UniqueConstraint(fields=('integration', 'message_id'), name='unique_synced_message_per_integration'),
        ),
    ]
