# Generated by Django 4.2.21 on 2026-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emailsyncedmessage_emailsuggestion_ai_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsuggestion',
            name='task_type_hint',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('long_term', 'Long Term')], max_length=10),
        ),
    ]
