# Generated by Django 4.2.21 on 2026-03-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_ragchunk_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_due', 'Long-term Task Due Date'), ('daily_task', 'Daily Task'), ('event_offset', 'Event Offset')], max_length=20)),
                ('remind_at_time', models.TimeField(blank=True, null=True)),
                ('offset_minutes', models.IntegerField(blank=True, null=True)),
                ('channel_email', models.BooleanField(default=False)),
                ('channel_telegram', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_connect_token', models.CharField(blank=True, max_length=64)),
                ('telegram_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_email_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_telegram_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='main_ragchu_user_id_fc3bb3_idx',
            old_name='ragchunk_user_key',
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='main_ragchu_note_id_eba4da_idx',
            old_name='ragchunk_note_idx',
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='main_ragchu_subject_eaf1e7_idx',
            old_name='ragchunk_subject_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='main.event'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='main.task'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('task__isnull', False), ('event__isnull', True)), models.Q(('task__isnull', True), ('event__isnull', False)), _connector='OR'), name='reminder_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(('channel_email', True), ('channel_telegram', True), _connector='OR'), name='reminder_requires_channel'),
        ),
    ]
